### ISSUE TITLE
autoconf 2.70 - configure.ac has obselete macros

### ISSUE THREAD

**Issue by gene-git** [trusteddomainproject/OpenDKIM#114]
autoconf 2.70 was released on December 8th and brings quite a few changes, some are not backward compatible. The release note is here:

https://lwn.net/Articles/839395/
configure.ac needs to be updated

There are now warnings during build:
configure.ac:65: warning: The macro `AC_PROG_CC_C99' is obsolete. 
configure.ac:67: warning: The macro `AC_PROG_LIBTOOL' is obsolete. 
configure.ac:2648: warning: AC_OUTPUT should be used without arguments.

**Comment by thegushi** [comment]
Hey Gene,

Sorry for the radio silence on this -- I've gone through and applied some autoconf changes on the develop branch but on my own private repo over at thegushi/OpenDKIM (develop branch).  If you'd care to check that out, I'd love to declare this a success.

**Comment by gene-git** [comment]
Hiya - 

1) yep - the configure looks clean now  - using your repo.

2) Aside - I see a bunch of array bounds like warnings from gcc 12. e.g.

In function ‘snprintf’,
    inlined from ‘main’ at t-test120.c:148:2:
/usr/include/bits/stdio2.h:54:10: note: ‘__builtin___snprintf_chk’ output between 17 and 4113 bytes into a destination of size 4097

3) FYI  - I have since replaced opendkim with other tools - I am happy to continue build tests tho.

4) Thanks! Success declared

gene

**Comment by gene-git** [comment]
Oh there are bunches of openssl deprecated warnings - looks like openssl3 clean up is needed too:

dkim.c:1288:17: warning: 'RSA_size' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]

Thats all I spotted :)

thanks again.

**Comment by thegushi** [comment]
At the very least, FreeBSD 13.1 and 12.4 (which are current) still use openssl 1.1.1 -- those warnings are going to be there for a bit.

**Comment by gene-git** [comment]
If were my code I would use 

#if OPENSSL_VERSION_NUMBER xxx

so code works on both older and current opensssl - and probably best to get that coded sooner than later - but then again its not up to me :)

thanks dan.

gene

**Comment by gene-git** [comment]
again if were up to me -  BSD is a pretty small minority of servers these days - I'd look to the linux world for what servers run more often - from what I see, all major linux distros now use openssl 3.x by default or optional ly-  redhat, fedora, debian, arch , suse (may be optional). But I would not look to bsd for guidance.  No market share.

**Comment by thegushi** [comment]
Thanks Gene.

We get a number of bug reports for BSD specifically, and while the market share isn't what linux is, I assure you there are people, including my day job, using it to drive critical internet infrastructure.

But sure, let's look to Linux:

My current mail server (running commercial Zimbra) is running Ubuntu LTS (not EOL yet):

# openssl version
OpenSSL 1.1.1  11 Sep 2018
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

How about my linux asterisk server, running Debian Buster (also not EOL)?

***@***.***:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
***@***.***:~$ openssl version
OpenSSL 1.1.1n  15 Mar 2022
***@***.***:~$

How about issue number https://github.com/trusteddomainproject/OpenDKIM/issues/158

1.1.1 isn't going away any time soon, though I'd really love to target only one version.  Of course, as soon as 1.1.1 dies, people will want us to support 3.1.0 or something, and some linux will make it the default (but not all of them will).

-Dan

**Comment by gene-git** [comment]
Ok :)

BTW to be clear - I wasn't suggesting removing openssl 1.1, rather merely having the code continue to work with 1.1 but in addition work with 3.x - that was the spirit of the #if x > y thing. Yep - there are lots of LTS still on 1.1.'

Anyway have great 2023 !
