### ISSUE TITLE
RequireSafeKeys false does not quiet "key data is not secure..."  log messages

### ISSUE THREAD

**Issue by myfirstnameispaul** [trusteddomainproject/OpenDKIM#124]
With `RequireSafeKeys false` in `opendkim.conf`, I am still getting the message:

    opendkim [7812]: example.com: key data is not secure: /home/user-data is writeable and owned by uid 1001 which is not the executing uid (118) or the superuser

Is there any way to quiet this?

**Comment by thegushi** [comment]
There is not.  You can put the keys into a fully safe path, or chown them to opendkim.  All requiresafekeys does is change this from an error (which makes it refuse to use the keys) into a warning.

This is cryptographic material, caution is warranted here.
