### ISSUE TITLE
Unable to build with lua >= 5.3

### ISSUE THREAD

**Issue by bib1963** [trusteddomainproject/OpenDKIM#142]
Not that it matters since this appears to be completely dead, but OpenDKIM cannot be built with anything greater than lua 5.2.

**Comment by gurnec** [comment]
Debian devs have been doing a great job of maintaining both this and OpenDMARC. In particular, [this patch](https://sources.debian.org/patches/opendkim/2.11.0~beta2-6/lua-5.3.patch/) adds support for Lua 5.3 and is part of Debian testing (bookworm).

**Comment by thegushi** [comment]
I’ve Previously given openDMARC some love and I want to do some focus on openDKIM as well. Your tickets are not falling on deaf ears.

**Comment by thegushi** [comment]
It looks like this was pulled in already in #70 -- if you'd like to test your build against the develop branch, I think you'll find things work (but feel free to push back here if you still see a problem)
