### ISSUE TITLE
opendkim-genkey Command not found

### ISSUE THREAD

**Issue by TomBertie** [trusteddomainproject/OpenDKIM#150]
In a clean VM with opendkim installed I now am getting command not found when I try to generate a key with opendkim-genkey

OS: CentOS 8 Stream
opendkim.x86_64: 2.11.0-0.28.el8

It is working fine on another VM running opendkim version 2.11.0-0.17.el8

Has anything changed?

**Comment by ghen2** [comment]
On EL8, it's packaged separately in `opendkim-tools`.

**Comment by TomBertie** [comment]
Thanks so much @ghen2.  Is this a recent change because on the other machine also running CentOS8 stream and OpenDKIM 2.11.0-0.17.el8 I can generate keys and don't have opendkim-tools installed

**Comment by ghen2** [comment]
No idea why they decided to split this (as well as libopendkim), it has the same dependencies etc.

**Comment by thegushi** [comment]
This is up to the packagers, and we don't manage this upstream.
