### ISSUE TITLE
opendkim: incompatible SSL versions

### ISSUE THREAD

**Issue by bacarrdy** [trusteddomainproject/OpenDKIM#23]
Hello,

Today i have installed opendkim on ubuntu 16.04.4 and got error when i tryed to start it:

May 31 11:06:02 mail opendkim[59911]: opendkim: incompatible SSL versions (library = 0x0100020bf, filter = 01000204f)

OpenDKIM version - opendkim 2.10.3-3build1
Openssl version - 1.0.2.g-1ubuntu4.12

After that i tryed to download source of openssl from openssl.org and compile it and there is the same error with:

openssl version
OpenSSL 1.1.0.h 27 Mar 2018

**Comment by dilyanpalauzov** [comment]
I think this is not a problem of opendkim, but a matter of how you compile the software.  If you
* compile openssl, and put its libraries in `/usr/local/lib(64)`,
* run `ldconfig`,
* run then `ldconfig -p|grep libcrypto` to verify that the library in `/usr/local/lib(64)` is found before the system library in `/usr/lib(64)`,
* rebuild and reinstall `opendkim`, and
* ensure it uses the library in `/usr/local/lib(64)` by running `ldd /usr/local/sbin/opendkim`

then there should be no problem.

I personally use `opendkim` with GnuTLS, for this you will need the fixes from https://github.com/trusteddomainproject/OpenDKIM/issues/19.

**Comment by alevesely** [comment]
As erroneously reported [here](https://sourceforge.net/p/opendkim/bugs/278/), in OpenSSL 1.1.0 or above the library will initialize itself automatically. A compatibility macro exists in ssl.h that maps SSL_library_init to OPENSSL_init_ssl, but the symbol is not defined.

Replacing the symbol as in the patch below works, but then it would not worl with OpenSSL 1.0.2 or below.

```diff
--- configure.ac.orig	2019-06-28 15:01:40.000000000 +0200
+++ configure.ac	2019-06-28 14:57:52.000000000 +0200
@@ -860,7 +860,7 @@
 	AC_SEARCH_LIBS([ERR_peek_error], [crypto], ,
 	               AC_MSG_ERROR([libcrypto not found]))
 
-	AC_SEARCH_LIBS([SSL_library_init], [ssl], ,
+	AC_SEARCH_LIBS([OPENSSL_init_ssl], [ssl], ,
 		[
 			if test x"$enable_shared" = x"yes"
 			then
@@ -874,9 +874,9 @@
 
 			# avoid caching issue - last result of SSL_library_init
 			# shouldn't be cached for this next check
-			unset ac_cv_search_SSL_library_init
+			unset ac_cv_search_OPENSSL_init_ssl_init
 			LIBCRYPTO_LIBS="$LIBCRYPTO_LIBS -ldl"
-			AC_SEARCH_LIBS([SSL_library_init], [ssl], ,
+			AC_SEARCH_LIBS([OPENSSL_init_ssl], [ssl], ,
 			               AC_MSG_ERROR([libssl not found]), [-ldl])
 		]
 	)
```

**Comment by simply-phil-1** [comment]
my error is:  
   opendkim: incompatible SSL versions (library = 0x030000000, filter = 030000020)

and occurs when libopendkim is built with a different ssl library to the main opendkim application.  The only way I could resolve the error message was with the "--disable-shared" config option

./configure --with-gnutls  --disable-shared

**Comment by alevesely** [comment]
You obviously compile opendkim with a version newer then the one used to compile libopendkim.  An alternative would be to compile the whole package, opendkim and its libraries, using the same environment.  That is, have ld.so.cache or  whatever point to the correct libopendkim.

IIRC opendkim is the only program using libopendkim, so not sharing the library isn't bad at all.  However, libgnutls is good to stay shared.
