### ISSUE TITLE
feedback log from compiling beta2

### ISSUE THREAD

**Issue by hdatma** [trusteddomainproject/OpenDKIM#37]
[opendkim-2.11.0-Beta2-compiler-stderr.log](https://github.com/trusteddomainproject/OpenDKIM/files/2935432/opendkim-2.11.0-Beta2-compiler-stderr.log)

**Comment by mskucherawy** [comment]
There's a ton of stuff here.  Was it all warnings or was this fatal?

**Comment by hdatma** [comment]
fatal

**Comment by hdatma** [comment]
Configuration, compilation and sequential test all terminate without error when applying the patches I posted in my issues.
