### ISSUE TITLE
dead project - alternatives?

### ISSUE THREAD

**Issue by ghost** [trusteddomainproject/OpenDKIM#50]
Since this project is dead...

What are some alternative milters that support DKIM? Preferably something that works in RHEL 8/CentOS 8.

Thank you.

**Comment by wangyu1314** [comment]
rspamd support dkim well.

**Comment by quanah** [comment]
amavisd-new is an alternative

**Comment by ghost** [comment]
Personally, I prefer specialised tools over general ones. I'm willing to give amavisd-new a try, but last time I checked, it would not install on CentOS 8 due to failed dependencies on some perl packages.

**Comment by jcapo** [comment]
And this

   https://github.com/fastmail/authentication_milter

John Capo
Tuffmail.com

**Comment by tjanez** [comment]
One that I found about recently is the combination of [dkimpy](https://launchpad.net/dkimpy/) & [dkimpy-milter](https://launchpad.net/dkimpy-milter).

> Preferably something that works in RHEL 8/CentOS 8.

There has been some recent progress around that, see [upstream bug #1851804](https://bugs.launchpad.net/dkimpy-milter/+bug/1851804).

**Comment by ghost** [comment]
opendkim is dead, long live dkimpy & dkimpy-milter. Issue resolved by moving on.

**Comment by quanah** [comment]
Looks like they're focusing on OpenARC now.

**Comment by ghost** [comment]
OpenARC is similarly dead. It has ... wait for it... 3 commits during the entire 2019!

if that is "focusing"...

**Comment by quanah** [comment]
@robo2bobo 

Given it's part of an ongoing RFC standard, there probably are times where there is nothing *to* develop while details are being hashed out.  Also, if something becomes feature complete and no obvious bugs, then would there be commits.  I'm not saying this is the case here for either of these projects, but just want to note that it is entirely possible for software to be functional and have no commit activity...

**Comment by stokito** [comment]
I see the next branch that has commits in 2018 https://github.com/trusteddomainproject/OpenDKIM/tree/next
It contains ed25519 support which is critical as for me.
The Debain (which is used on most mail servers) in fact has it's own fork
https://salsa.debian.org/debian/opendkim/

I see plenty of patches there
https://salsa.debian.org/debian/opendkim/-/tree/master/debian/patches
There is also 2 PRs in addition to 18 (!) PRs here.
This is a critical project for entire Internet so could you pull the patches that are already used in real life?


If the project is unmaintained then maybe you can give an access to this repo to Debian dev David Bürgin?

**Comment by thegushi** [comment]
> On Oct 18, 2022, at 20:54, Sergey Ponomarev ***@***.***> wrote:
> 
> 
> I see the next branch that has commits in 2018 https://github.com/trusteddomainproject/OpenDKIM/tree/next <https://github.com/trusteddomainproject/OpenDKIM/tree/next>
> It contains ed25519 support which is critical as for me.
> The Debain (which is used on most mail servers) in fact has it's own fork
> https://salsa.debian.org/debian/opendkim/ <https://salsa.debian.org/debian/opendkim/>
> I see plenty of patches there
> https://salsa.debian.org/debian/opendkim/-/tree/master/debian/patches <https://salsa.debian.org/debian/opendkim/-/tree/master/debian/patches>
> There is also 2 PRs in addition to 18 (!) PRs here.
> This is a critical project for entire Internet so could you pull the patches that are already used in real life?
> 
> If the project is unmaintained then maybe you can give an access to this repo to Debian dev David Bürgin?
> 
> 

It's not entirely unmaintained, but there is some technical debt, to be absolutely sure.  We're going to be pushing a release for the version that includes ED25519 support, but we also need to fix Autoconf support as well as ensure testing works with openssl 3, on several platforms (which means spinning up new test platforms).

-Dan

**Comment by davispuh** [comment]
So nowadays what people are using for DKIM? It looks like there haven't been new releases for OpenDKIM for many years and looks like no one reviews PRs.
I guess Rspamd is where to go.

**Comment by Neustradamus** [comment]
I have not commented here in the past, but I have created several tickets:
- https://github.com/trusteddomainproject/OpenDKIM/issues/256
- https://github.com/trusteddomainproject/OpenDKIM/issues/255
- https://github.com/trusteddomainproject/OpenDMARC/issues/290
- https://github.com/trusteddomainproject/OpenDMARC/issues/291
- ...

@arekm has done a ticket here:
- https://github.com/trusteddomainproject/OpenDMARC/issues/294

@olspanner has done this ticket here:
- https://github.com/trusteddomainproject/OpenDKIM/issues/25
