### ISSUE TITLE
Latest tarballs cannot be built using ./configure && make

### ISSUE THREAD

**Issue by glts** [trusteddomainproject/OpenDKIM#59]
The tarballs published at https://github.com/trusteddomainproject/OpenDKIM/releases cannot be built and installed using the classic procedure `./configure` `make` `make install`. This used to work in the past, and it should work according to the INSTALL file.

    $ curl -LO https://github.com/trusteddomainproject/OpenDKIM/archive/rel-opendkim-2-11-0-Beta2.tar.gz
    $ tar xvf rel-opendkim-2-11-0-Beta2.tar.gz
    $ cd OpenDKIM-rel-opendkim-2-11-0-Beta2
    $ ./configure
    configure: error: cannot find install-sh, install.sh, or shtool in build-aux "."/build-aux

On a system that has Autotools, `autoreconf -i` can of course generate the missing files, but this additional step shouldn’t be necessary.

**Comment by egberts** [comment]
Agreed with `autoreconf -i`.  That should have been done only by the maintainer, and not us debugger/developer.

Ideally for developers (not maintainer), autotool is best used as followed during development:
For production, take out the `--enable-debug`.

```
libtoolize -v -i --copy --force
aclocal -I m4 -Wall
autoheader -Wall -v
autoconf -Wall -v
automake --add-missing --force-missing --foreign --copy --warnings=override -Wall
./configure --enable-debug --prefix=/usr
```

And no, OpenDKIM doesn't build well ... yet, particularly in Debian 10.2.

References:

* https://sourceforge.net/p/opendkim/bugs/250/
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=948504
* #53 and #54

**Comment by glts** [comment]
@egberts OpenDKIM builds fine on Debian. You need to install the [build dependencies](https://sources.debian.org/src/opendkim/2.11.0%7Ebeta2-1/debian/control/#L5-L8) if you want to build from source. strl* and friends are provided by libbsd.

**Comment by egberts** [comment]
I fixed my issue by installing libbsd-dev,Debian package.

**Comment by martinbogo** [comment]
Not a bug... this is as designed, and you must install all dependencies before your build.

**Comment by glts** [comment]
@martinbogo You closed this by mistake. The discussion above is a distraction.

It is still true that the latest released tarballs cannot be built using `./configure && make`, regardless of presence of dependencies.
